### ISSUE TITLE
Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by 217Wilder-User1** [psirenny/gulp-fluent-ffmpeg#2]
@psirenny I'm using NPM gulp-fluent-ffmpeg 1.0.2 and I'm running into an error.  I used the same code gulp.task code in the readme and when I run the task I get an `Error: Cannot find ffmpeg`

Any thoughts on why this is happening?  Am I Missing something?

```
[13:56:13] Starting 'audio'...
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find ffmpeg
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\lib\processor.js:131:22
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:486:20
    at nextTask (C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:5008:33)
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:5015:17
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:339:31
Process terminated with code 8.
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:847:20
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\lib\capabilities.js:116:11
    at C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\lib\utils.js:223:16
    at F (C:\Projects\CODE\FFMpeg-Gulp\node_modules\gulp-fluent-ffmpeg\node_modules\fluent-ffmpeg\node_modules\which\which.js:69:16)
```

Here's the gulpfile.js code I'm using

```
var gulp = require('gulp');
var ffmpeg = require('gulp-fluent-ffmpeg');

gulp.task('audio', function () {
    // transcode ogg files to mp3
    return gulp.src('src/audio/*.ogg')
      .pipe(ffmpeg('mp3', function (cmd) {
          return cmd
            .audioBitrate('128k')
            .audioChannels(2)
            .audioCodec('libmp3lame')
      }))
      .pipe(gulp.dest('dest/audio'));
});
```

Package.json = 

```
{
    "name": "ffmpegtest",
    "version": "1.0.0",
    "private": true,
  "dependencies": {

  },
  "devDependencies": {
    "gulp-fluent-ffmpeg": "1.0.2",
    "gulp": "3.9.1",
    "gulp-util": "3.0.7"
  }
}
```

**Comment by psirenny** [comment]
You either don't have the ffmpeg binary installed or the path to the binary can't be found. This plugin is basically a wrapper around the [node-fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) library. The readme on that library has instructions on the version of ffmpeg you'll need (>= 0.9) and how to configure the path to the binary.

If you're on windows you'll almost certainly need to configure your `%PATH` environment variable. I'd follow up on that repo though, as I'm sure there have been other issues similar to your own that have been resolved.

**Comment by 217Wilder-User1** [comment]
@psirenny Great catch with the %PATH.  I had a version of Node installed by Visual Studio and the %PATH was in environmental variables.  I downloaded the latest version of Node, installed, and the paths were registered correctly.  I also needed to add a `.setFfmpegPath("C:\\folderlocations\\bin\\ffmpeg.exe")` to the sample code and it worked.  

Question: Does your code only work with audio files?

**Comment by psirenny** [comment]
Aha! I'm glad you got that resolved.

The plugin should work with video files as well. My own use case for this has been with audio so the only usage example reflects that.

**Comment by 217Wilder-User1** [comment]
@psirenny I was able to get the video working!  Here's some example code.

```
var gulp = require("gulp");
var ffmpeg = require('gulp-fluent-ffmpeg');

gulp.task('video', function () {
    // transcode mp4 to mp4
    return gulp.src('./src/video/*.mp4')
      .pipe(ffmpeg('mp4', function (cmd) {
          return cmd
              .setFfmpegPath("C:\\Projects\\CODE\\FFMpeg-testing\\bin\\ffmpeg.exe")
              .outputOptions('-loglevel warning')
              .outputOptions('-bsf:v h264_mp4toannexb')
              .outputOptions('-bsf:v dump_extra')
              .outputOptions('-movflags frag_keyframe+empty_moov')
            .on('error', function (err, stdout, stderr) {
                //console.log('An error occurred: ' + err.message);
                console.log('an error happened: ' + err.message, stdout, stderr);
            })
            .on('end', function () {
                console.log('Processing finished !');
            })
      }))
      .pipe(gulp.dest('./dest/video'));
});
```
